$services = @(
    @{
        folder="haridra-ganapathy-homam"
        component="HaridraGanapathyHomamPage"
        title="Haridra Ganapathy Homam"
        description="Special homam to Lord Ganesha with turmeric for removing obstacles and success."
        image="/services/virtual/Haridra Ganapathy Homam.png"
        price="₹9,999.00 – ₹20,000.00"
        economyPrice="Rs. 9,999"
        standardPrice="Rs. 12,999"
        premiumPrice="Rs. 20,000"
        objective="To invoke Lord Ganesha with turmeric (Haridra) for removal of obstacles, prosperity, and success in all endeavors."
        deity="Lord Haridra Ganapathy (Turmeric Ganesha)"
        purpose="Removal of obstacles, Success in new ventures, Prosperity and abundance, Health and well-being, Protection from negative forces"
    },
    @{
        folder="maha-mrutyunjaya-homam"
        component="MahaMrutyunjayaHomamPage"
        title="Maha Mrutyunjaya Homam"
        description="Powerful ritual for health, longevity, and victory over death."
        image="/services/virtual/Maha Mrutyunjaya Homam.jpeg"
        price="₹15,000.00 – ₹35,000.00"
        economyPrice="Rs. 15,000"
        standardPrice="Rs. 25,000"
        premiumPrice="Rs. 35,000"
        objective="To invoke Lord Shiva through the powerful Maha Mrutyunjaya mantra for health, longevity, and protection."
        deity="Lord Shiva (Conqueror of death)"
        purpose="Healing from serious illnesses, Protection from untimely death, Longevity and vitality, Spiritual liberation, Peace and fearlessness"
    },
    @{
        folder="maha-sudarshana-homam"
        component="MahaSudarshanaHomamPage"
        title="Maha Sudarshana Homam"
        description="Sacred fire ritual to Lord Sudarshana for protection and removal of negative forces."
        image="/services/virtual/Maha Sudarshana Homam.jpeg"
        price="₹15,000.00 – ₹35,000.00"
        economyPrice="Rs. 15,000"
        standardPrice="Rs. 25,000"
        premiumPrice="Rs. 35,000"
        objective="To invoke Lord Sudarshana (the divine discus of Lord Vishnu) for protection and destruction of negative energies."
        deity="Lord Sudarshana Chakra (Divine weapon of Lord Vishnu)"
        purpose="Protection from enemies and evil forces, Removal of black magic and negative energies, Victory over obstacles, Health and prosperity, Spiritual progress"
    },
    @{
        folder="mahalakshmi-homam"
        component="MahalakshmiHomamPage"
        title="MAHALAKSHMI HOMAM"
        description="Invoke Goddess Mahalakshmi for wealth, prosperity, and abundance."
        image="/services/virtual/MAHALAKSHMI HOMAM.jpeg"
        price="₹15,000.00 – ₹35,000.00"
        economyPrice="Rs. 15,000"
        standardPrice="Rs. 25,000"
        premiumPrice="Rs. 35,000"
        objective="To invoke Goddess Mahalakshmi for wealth, prosperity, abundance, and overall well-being."
        deity="Goddess Mahalakshmi (Goddess of wealth and prosperity)"
        purpose="Financial prosperity and wealth, Business success, Removal of debts and financial obstacles, Abundance and luxury, Family harmony and happiness"
    },
    @{
        folder="mahalakshmi-puja"
        component="MahalakshmiPujaPage"
        title="MAHALAKSHMI PUJA"
        description="Traditional puja to Goddess Mahalakshmi for financial prosperity and blessings."
        image="/services/virtual/MAHALAKSHMI PUJA.jpeg"
        price="₹9,999.00 – ₹20,000.00"
        economyPrice="Rs. 9,999"
        standardPrice="Rs. 12,999"
        premiumPrice="Rs. 20,000"
        objective="To perform traditional puja to Goddess Mahalakshmi for financial prosperity and her divine blessings."
        deity="Goddess Mahalakshmi (Goddess of wealth)"
        purpose="Financial growth and stability, Business prosperity, Removal of poverty, Blessings for home and family, Overall abundance"
    },
    @{
        folder="mrutyunjaya-homam"
        component="MrutyunjayaHomamPage"
        title="Mrutyunjaya Homam"
        description="Vedic ritual to Lord Shiva for health, protection, and overcoming difficulties."
        image="/services/virtual/Mrutyunjaya Homam.jpeg"
        price="₹15,000.00 – ₹35,000.00"
        economyPrice="Rs. 15,000"
        standardPrice="Rs. 25,000"
        premiumPrice="Rs. 35,000"
        objective="To invoke Lord Shiva through Mrutyunjaya mantra for health, protection, and overcoming life\'s difficulties."
        deity="Lord Shiva (Conqueror of death)"
        purpose="Health and healing, Protection from accidents and dangers, Overcoming chronic illnesses, Longevity, Mental peace and strength"
    },
    @{
        folder="rudra-ekadashi-homam"
        component="RudraEkadashiHomamPage"
        title="Rudra Ekadashi Homam"
        description="Special homam on Ekadashi for Lord Shiva\'s blessings and spiritual growth."
        image="/services/virtual/rudra-ekadashi-homam.png"
        price="₹15,000.00 – ₹35,000.00"
        economyPrice="Rs. 15,000"
        standardPrice="Rs. 25,000"
        premiumPrice="Rs. 35,000"
        objective="To perform Rudra homam on the auspicious Ekadashi day for Lord Shiva\'s blessings and spiritual advancement."
        deity="Lord Shiva (Supreme consciousness)"
        purpose="Spiritual growth and enlightenment, Purification of sins, Blessings and divine grace, Peace and tranquility, Liberation (Moksha)"
    },
    @{
        folder="sadakshari-durga-gayatri-homam"
        component="SadakshariDurgaGayatriHomamPage"
        title="Sadakshari Durga Gayatri Homam"
        description="Powerful homam invoking Goddess Durga through Sadakshari mantra."
        image="/services/virtual/Sadakshari Durga Gayatri Homam.jpeg"
        price="₹15,000.00 – ₹35,000.00"
        economyPrice="Rs. 15,000"
        standardPrice="Rs. 25,000"
        premiumPrice="Rs. 35,000"
        objective="To invoke Goddess Durga through the powerful six-syllable (Sadakshari) Gayatri mantra for protection and blessings."
        deity="Goddess Durga (Divine Mother)"
        purpose="Protection from all evils, Spiritual power and strength, Success in endeavors, Removal of obstacles, Divine grace and blessings"
    },
    @{
        folder="saraswathi-poojai"
        component="SaraswathiPoojaiPage"
        title="SARASWATHI POOJAI"
        description="Sacred puja to Goddess Saraswathi for knowledge, wisdom, and arts."
        image="/services/virtual/SARASWATHI POOJAI.png"
        price="₹9,999.00 – ₹20,000.00"
        economyPrice="Rs. 9,999"
        standardPrice="Rs. 12,999"
        premiumPrice="Rs. 20,000"
        objective="To worship Goddess Saraswathi for knowledge, wisdom, education, and mastery in arts and learning."
        deity="Goddess Saraswathi (Goddess of knowledge and arts)"
        purpose="Academic excellence, Wisdom and intelligence, Success in arts and music, Clear speech and communication, Creative abilities"
    },
    @{
        folder="shatru-samhara-homam"
        component="ShatruSamharaHomamPage"
        title="Shatru Samhara Homam"
        description="Ritual for protection from enemies and victory over opposition."
        image="/services/virtual/Shatru Samhara Homam.jpeg"
        price="₹15,000.00 – ₹35,000.00"
        economyPrice="Rs. 15,000"
        standardPrice="Rs. 25,000"
        premiumPrice="Rs. 35,000"
        objective="To invoke divine energies for protection from enemies and victory over opposition and adversaries."
        deity="Lord Narasimha and other protective deities"
        purpose="Protection from enemies, Victory in competitions and legal matters, Removal of evil influences, Courage and strength, Success over adversaries"
    },
    @{
        folder="sidhi-vinayaga-puja"
        component="SidhiVinayagaPujaPage"
        title="SIDHI VINAYAGA PUJA"
        description="Special puja to Lord Ganesha for success, prosperity, and wish fulfillment."
        image="/services/virtual/SIDHI VINAYAGA PUJA.jpeg"
        price="₹9,999.00 – ₹20,000.00"
        economyPrice="Rs. 9,999"
        standardPrice="Rs. 12,999"
        premiumPrice="Rs. 20,000"
        objective="To worship Sidhi Vinayaga (Ganesha who grants success) for prosperity, wish fulfillment, and removal of obstacles."
        deity="Sidhi Vinayaga (Lord Ganesha - Bestower of success)"
        purpose="Success in all endeavors, Wish fulfillment, Removal of obstacles, Prosperity and wealth, Divine blessings"
    },
    @{
        folder="swayamvara-parvathi-homam"
        component="SwayamvaraParvathiHomamPage"
        title="Swayamvara Parvathi Homam"
        description="Sacred ritual for marriage blessings and finding suitable life partner."
        image="/services/virtual/Swayamvara Parvathi Homam.png"
        price="₹15,000.00 – ₹35,000.00"
        economyPrice="Rs. 15,000"
        standardPrice="Rs. 25,000"
        premiumPrice="Rs. 35,000"
        objective="To invoke Goddess Parvathi in her Swayamvara form for blessings in finding a suitable life partner and marital bliss."
        deity="Goddess Swayamvara Parvathi (Goddess of marriage)"
        purpose="Finding suitable life partner, Timely marriage, Marital harmony, Removal of marriage obstacles, Blessings for happy married life"
    },
    @{
        folder="vancha-kalpalatha-maha-ganapathi-homam"
        component="VanchaKalpalathaMahaGanapathiHomamPage"
        title="Vancha Kalpalatha Maha Ganapathi Homam"
        description="Powerful Ganesha homam for fulfillment of desires and wishes."
        image="/services/virtual/Vancha Kalpalatha Maha Ganapathi Homam.png"
        price="₹15,000.00 – ₹35,000.00"
        economyPrice="Rs. 15,000"
        standardPrice="Rs. 25,000"
        premiumPrice="Rs. 35,000"
        objective="To invoke Vancha Kalpalatha Maha Ganapathi (wish-fulfilling Ganesha) for manifestation of desires and wishes."
        deity="Vancha Kalpalatha Maha Ganapathi (Wish-fulfilling Ganesha)"
        purpose="Fulfillment of desires and wishes, Success in endeavors, Prosperity and abundance, Removal of all obstacles, Divine blessings for aspirations"
    }
)

Write-Output "Will create $($services.Count) service files"
